# Generated by Django 3.2.6 on 2021-08-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colorOptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeOptions',
            field=models.TextField(blank=True),
        ),
    ]
