# Generated by Django 3.2.6 on 2021-08-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210826_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.25, max_digits=5),
            preserve_default=False,
        ),
    ]
