# Generated by Django 3.2.6 on 2021-08-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toppings',
        ),
    ]
